// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "player":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image2":
            case "background1":return img`
ccccccccccccccccccccccccccccccccccccccccccccccccfffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccfffcccfffcccccccccccccccccccccccccccccccccccccccccccccccccccccfffcccfffcccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccffcccbbbcccffcccccccccccccccccccccccccccccccccccccccccccccccccffcccbbbcccffcccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccf11bbbbbbbbb11fcccccccccccccccccccccccccccccccccccccccccccccccf11bbbbbbbbbc1fccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccf1bbbbbbfbbbbbb1fcccccccccccccccccccccccccccccccccccccccccccccf1bbbbbbfbbbbbb1fcccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccf1bbbfffffbbbbfcccccccccccccccccccccccccccccccccccccccccccccccfbbbbfffffbb11fccccccccccccccccccccccccccccccccccccccccc
ffffffffffffffffffffffffffffffffffffffffffffffffbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbfffffffffffffffffffffffffffffffffffffffffffffff
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbf1fbfbfcccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccfffffffffccccccccccccccccccccfbfbf1fbfccccccccccccccccccccccfffffffffccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccfffffffffcccccccccccccccc
cccccccccccccfffbbbbbbbbbfffcccccccccccccccccfbfbfbfbfcccccccccccccccccccfffbbbbbbbbbfffcccccccccccccccccccfbfbfbfbfccccccccccccccccfffbbbbbbbbbfffccccccccccccc
ccccccccccfffbbbcccccccccbbbfffccccccccccccccfbfbfbfbfccccccccccccccccfffbbbcccccccccbbbfffccccccccccccccccfbfbfbfbfcccccccccccccfffbbbcccccccccbbbfffcccccccccc
ccccccccffbbbcccccbbbbbcccccbbbffccccccccccccfbfbfbfbfccccccccccccccffbbbcccccbbbbbcccccbbbffccccccccccccccfbfbfbfbfcccccccccccffbbbcccccbbbbbcccccbbbffcccccccc
cccccccfbbcccccbbbcccccbbbcccccbbfcccccccccccfbfbfbfbfcccccccccccccfbbcccccbbbcccccbbbcccccbbfcccccccccccccfbfbfbf1fccccccccccfbbcccccbbbcccccbbbcccccbbfccccccc
ccccccfbccccbbbcccccccccccbbbccccbfccccccccccfbfbfbfbfccccccccccccfbccccbbbcccccccccccbbbccccbfccccccccccccfbfbfbf1fcccccccccfbccccbbbcccccccccccbbbccccbfcccccc
ccccccfbccbbcccccccc1ccccccccbbccbfccccccccccfbfbfbfbfccccccccccccfbccbbccccccc1cccccccccbbccbfccccccccccccfbfbfbf1fcccccccccfbccbbcccccccccccccccccbbccbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccccccccccccccccbcbfccccccccccccfbfbfbf1fcccccccccfbcbccccccccccccc1cccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccccccccccccccccbcbfccccccccccccf1fbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccffcccffcccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccccccccccccccccbcbfccccccccccccf1fbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbccc1cccccccfcfcccccccbcbfccccccccccf1fbfbfbfccccccccccccfbcbcc1ccccccccccccccccccbcbfccccccccccccf1fbfbfbfcccccccccfbcbcccccccc1ccccccccccccbcbfcccccc
ccccccfbcbccccccccccccfccccccccbcbfccccccccccf1fbfbfbfccccccccccccfbcbccccccccccccccc1cccccbcbfccccccccccccf1fbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccf1fbfbfbfccccccccccccfbcbccccccccfccccccccccccbcbfccccccccccccf1fbfbfbfcccccccccfbcbcccccccccccccccc1ccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccf1fbfbfbfccccccccccccfbcbcccccccfcccccccccccccbcbfccccccccccccf1fbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccfcccccccccccccbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccc1ccccccccccccbcbfcccccc
ccccccfbcbccccccccccccccccccc1cbcbfccccccccccfbfbfbfbfccccccccccccfbcbccccccfccccccccccccccbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccc1ccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbccccffc1cccccccccccccbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccfcccccccccccccccccbcbfccccccccccccfbfbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccccccccccccccccbcbfccccccccccccfbfbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccccccccccccccccccccbcbfccccccccccccfbfbfbf1fcccccccccfbcbcccccccccccccccc1ccccbcbfcccccc
ccccccfbcbcccccccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbccccccccccccccc1cccccbcbfccccccccccccfbfbfbf1fcccccccccfbcbccc1cccccccccccccccccbcbfcccccc
ccccccfbcbcccecccccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbccccccccccccccccccccfbcbfccccccccccccfbfbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccffcccffecccc1cccccbcbfccccccccccfbfbfbf1fccccccccccccfbcbccccccccccccccccccfffbcbfccccccccccccfbfbfbf1fcccccccccfbcbccccccccccc1cccccccccbcbfcccccc
ccccccfbcbcccccffffccccccccccccbcbfccccccccccfbfbfbf1fccccccccccccfbcbccc1cccccccfcccccccfcbcbfccccccccccccfbfbfbf1fcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbccccfecfcccccccccccccbcbfccccccccccfbfbfbf1fccccccccccccfbcbccccccccffcfcccccccddbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbccccccfcfccccccccccccbcbfccccccccccfbfbfbf1fccccccccccccfbcbccccfcccccfccccccddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbcccccffccfcccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccfecccccfcccdddddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbcccccccccccccccccccccbcbfcccccc
ccccccfbcbccccccfccfcccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcfffcccccddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbcfcccccccccfccccffcccbcbfcccccc
ccccccfbcbcccccecccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccfccdddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbffccc1cccccffcfefccccbcbfcccccc
ccccccfbcbcccccfcccccccccccccccbcbfccccccccccfbfbfbfbfccccccccccccfbcbcccfdddddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbcccccccccccceffccccccbcbfcccccc
ccccccfbcbccccfccccccccccccccccbcbfccccccccccfbf1fbfbfccccccccccccfbcbccdddddddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbccccccccccccccfffccccbcbfcccccc
ccccccfbcbccccdddddccccccccfffcbcbfccccccccccfbf1fbfbfccccccccccccfbcbcddddddddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbdcccccccccccffefcccddbcbfcccccc
ccccccfbcbccddddddddddcccddddddbcbfccccccccccfbf1fbfbfccccccccccccfbcbdddddddddddddddddddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbdddddcccccccccfccddddbcbfcccccc
ccccccfbcbdddddddddddddddddddddbcbfccccccccccfbf1fbfbfccccccccccccfbcbddddddddddddddd1111ddbcbfccccccccccccfbfbfbfbfcccccccccfbcbddddddddddccccfddddddbcbfcccccc
ccccccfbcbdddddddddddddddddddddbcbfccccccccccfbf1fbfbfccccccccccccfbcbdddddddddddddd11111ddbcbfccccccccccccfbfbfbfbfcccccccccfbcbdddddddddddddddddddddbcbfcccccc
ccccccfbcbdddddddddddddddd111ddbcbfccccccccccfbf1fbfbfccccccccccccfbcbddddddddddddddd111dddbcbfccccccccccccfbfbfbfbfcccccccccfbcbdddddddddddddddddddddbcbfcccccc
ccccccfbcbddddddddddddddd1111ddbcbfccccccccccfbfbfbfbfccccccccccccfbcb1ddddddddddddddddddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbddd1111111dddddddddddbcbfcccccc
ccccccfbcbddddddddddddddd1111ddbcbfccccccccccfbfbfbfbfccccccccccccfbcb11dddddddddddddddddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbddd111111111dddddddddbcbfcccccc
ccccccfbcbdddddddddddddddddddddbcbfccccccccccfbfbfbfbfccccccccccccfbcb11dddddddddddddddddddbcbfccccccccccccfbfbfbfbfcccccccccfbcbddd111111111dddddddddbcbfcccccc
ccccccfbcbdddddddddddddddddddddbcbfccccccccccfbfbfbfbfccccccccccccfbcb1ddddddddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbdddddddddddddddddddddbcbfcccccc
ccccccfbcbdddddddddddddddddddddbcbfccccccccccfbfbfbfbfccccccccccccfbcbdddddddddddddddddddddbcbfccccccccccccf1fbfbfbfcccccccccfbcbdddddddddddddddddddddbcbfcccccc
ccccccfbcbbbbbbbbbbbbbbbbbbbbbbbcbfccccccccccfbfbfbfbfccccccccccccfbcbbbbbbbbbbbbbbbbbbbbbbbcbfccccccccccccf1fbfbfbfcccccccccfbcbbbbbbbbbbbbbbbbbbbbbbbcbfcccccc
ccccfffbcccccccccccccccccccccccccbfffccccccccfbfbfbfbfccccccccccfffbcccccccccccccccccccccccccbfffccccccccccf1fbfbfbfcccccccfffbcccccccccccccccccccccccccbfffcccc
ccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccccccccfbfbfbfbfccccccccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccccccccccf1fbf1fbfcccccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfcccc
ccccfbbbbbfffffbfffffbbfbfbbfffffbbbfccccccccfbfbfbfbfccccccccccfbbbbfbbbfbbffbffbffbffbfffffbbbfccccccccccf1fbf1fbfcccccccfbbbbbfbbbbbbbfffbffbbbbfbbbfbbbfcccc
ccccfbbbbbfbbbfbfbfbfbbbfbbbfbbbfbbbfccccccccfbfbfbfbfccccccccccfbbbfffffffbfbbbfbbbfbbbfbbbfbbbfccccccccccf1fbf1fbfcccccccfbbbbbfbfbbbbbfbbbbfbbbbbfbfbbbbfcccc
ccccfbbbfffbfbfbffbffbfffffbfbfbfbbbfccccccccfbfbfbfbfccccccccccfbbbfbbfbbfbfffffbbfbfbbffbffbbbfccccccccccfbfbf1fbfcccccccfbbbbbfffbbbbbfbbbbfbffbbbfbbbbbfcccc
ccccfbbbbbbbbbfbfbbbfbbfbfbbfbfbfbbbfccccccccfbfbfbfbfccccccccccfbbbfffffffbfbfbfbbfbfbbfbbbfbbbfccccccccccfbfbf1fbfcccccccfbbbbbfbfbbbbbffbbbfbfbbbfbfbbfffffcc
ccccfbbbbbbbbbfbffbffbbfbfbbfbbbfbbbfccccccccf1fbfbfbfccccccccccfbbbbbfffbbbfbbbfbbbfbbbfffffbbbfccccccccccfbfbfbfbfcccccccfbbfbbfffbbbfffbbbbfbfbbbfffbfbbbbbfc
ccccfbbbbbfffffbfbbbfbfbbbfbfffffbbbfccccccccfbfbfbfbfccccccccccfbbbbffbffbbffbffbffbffbfffffbbbfccccccccccfbfbfbfbfcccccccfbbbffbbbffbfbbbbbbfffbbfbbbffbbbbbbf
ccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccccccccfbfbfbfbfccccccccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfccccccccccfbfbfbfbfcccccccfbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbf
ccccfffffffffffffffffffffffffffffffffccccccccfbfbfbfbfccccccccccfffffffffffffffffffffffffffffffffccccccccccfbfbfbfbfcccccccffffffffffffffffffffffffffffffbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbf1fbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
ffffffffffffffffffffffffffffffffffffffffffffffbfbfbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbfbfbffffffffffffffffffffffffffffffffffffffbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccf1fbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfcccccccccccccccccccccccccccccccccccccccccccccccccccccfbfbfbfbfccccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccfffffbfbfffffcccccccccccccccccccccccccccccccccccccccccccccccccfffffbfbfffffccccccccccccccccccccccccccccccccccfbbbbbbf
ccccccccccccccccccccccccccccccccccccccccccf11bbfffffbb11fcccccccccccccccccccccccccccccccccccccccccccccccf11bbfffffbbb1fcccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccf1bbbbbbfbbbbbb1fcccccccccccccccccccccccccccccccccccccccccccccf1bbbbbbfbbbbbb1fccccccccccccccccccccccccccccccccfbbbbbbf
ccccccccccccccccccccccccccccccccccccccccccf11bbbbbbbbb11fcccccccccccccccccccccccccccccccccccccccccccccccf11bbbbbbbbb11fcccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccff11dbbbdddffcccccccccccccccccccccccccccccccccccccccccccccccccff11dbbbdd1ffccccccccccccccccccccccccccccccccccfbbbbbbf
cccccccccccccccccccccccccccccccccccccccccccccfffdddfffcccccccccccccccccccccccccccccccccccccccccccccccccccccfffdddfffccccccccccccccccccccccccccccccccccccfbbbbbbf
ccccccccccccccccccccccccccccccccccccccccccccccccfffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffcccccccccccccccccccccccccccccccccccccccfbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfffffffffffffffffffbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb1111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb11111bbbbbbbbbbbb1111111bbbbbbbbbbbbbbbbbbbbb11111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbb111111111111bbbbbbbbbbbbbbbbbbbbbbb1111111bbbbbbbbbbb111111111111111111111bbbbbbbbbb11111111bbbb11111bbbbbbbbbb111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbb11111111111111111111111bbbbbbbbb11111111bb1111111111111111111111111111111111111111111111111111111111b1111111111bbbbbb11111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbb111111111111111111111111111bbb1111111111111111111111111111111111111111111111111111111111111111111111111111111111111bbbb111111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bb111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bb111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111d11111111111111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbd11111111111111111111111111dd1ddddd1111111111111ddddddddd1111111111111111111111111111111111111111111111ddddddddd11dddddd111111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbddd1111111111111111111111dddddbbbdd11111111dddddbbbbbbbdddd111111111111111111111111dd11111111111dddddddbbbbbbbdddbbbbbdddd111111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbddddddd1111111111111ddddbbbbbbbbddddddddddbbbbbbbbbbbbbbdddddddddddddddd1dd11ddddddddddddddddddbbbbbdbbbbbbbbbbbbbbbbbbdddd111111fbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbdddd11111111dddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddbdddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbdddddddfbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbddddddddddbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbf
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfbbbbbbbbbbbbbbbbbbbbbbbbf
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
